version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - local-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    networks:
      - local-network

  service-a:
    build:
      context: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - otel-collector
    networks:
      - local-network
      
  service-b:
    build:
      context: ./service-b
    ports:
      - "8081:8081"
    environment:
      - WEATHERAPI_KEY={YOUR_WEATHERAPI_KEY}
    depends_on:
      - zipkin
      - otel-collector
    networks:
      - local-network

networks:
  local-network:
    driver: bridge