version: '3.8'

services:
  service-a:
    build:
      context: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - service-b
  service-b:
    build:
      context: ./service-b
    ports:
      - "8081:8081"
    environment:
      - WEATHERAPI_KEY={YOUR_WEATHERAPI_KEY}